version: "3"
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - elastic
      mem_limit: 2048M
      mem_reservation: 1024M
      restart: always
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      environment:
        - discovery.type=single-node
    kibana:
      image: docker.elastic.co/kibana/kibana:7.17.4
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_URL=http://localhost:9200
      networks:
        - elastic
      mem_limit: 512M
      mem_reservation: 256M
      restart: always
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
    apm-server:
      image: docker.elastic.co/apm/apm-server:7.17.4
      ports:
        - "8200:8200"
      networks:
        - elastic
      restart: always
      depends_on:
        - elasticsearch
      environment:
        - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      command: ["apm-server", "-e", "-E", "output.elasticsearch.hosts=[http://elasticsearch:9200]"]    

volumes:
  elasticsearch-data:
    driver: local
networks:
  elastic:
    driver: bridge
